"""generate all tables

Revision ID: 93914f7e145d
Revises: 3544828f52df
Create Date: 2022-09-10 22:12:51.648756

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93914f7e145d'
down_revision = '3544828f52df'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
